misago/admin/urls.py
from django.conf.urls import url

from misago import admin

from .views import auth, index


urlpatterns = [
    # "misago:admin:index" link symbolises "root" of Misago admin links space
    # any request with path that falls below this one is assumed to be directed
    # at Misago Admin and will be checked by Misago Admin Middleware
    url(r'^$', index.admin_index, name='index'),
    url(r'^resolve-version/$', index.check_version, name='check-version'),
    url(r'^logout/$', auth.logout, name='logout'),
]

# Discover admin and register patterns
admin.discover_misago_admin()
urlpatterns += admin.urlpatterns()

misago/legal/urls.py
from django.conf.urls import url

from .views import privacy_policy, terms_of_service


urlpatterns = [
    url(r'^privacy-policy/$', privacy_policy, name='privacy-policy'),
    url(r'^terms-of-service/$', terms_of_service, name='terms-of-service'),
]

misago/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from misago.conf import settings
from misago.core.views import forum_index


app_name = 'misago'

# Register Misago Apps
urlpatterns = [
    url(r'^', include('misago.legal.urls')),
    url(r'^', include('misago.users.urls')),
    url(r'^', include('misago.categories.urls')),
    url(r'^', include('misago.threads.urls')),
    url(r'^', include('misago.search.urls')),

    # default robots.txt
    url(
        r'^robots.txt$',
        TemplateView.as_view(content_type='text/plain', template_name='misago/robots.txt')
    ),

    # "misago:index" link symbolises "root" of Misago links space
    # any request with path that falls below this one is assumed to be directed
    # at Misago and will be handled by misago.views.exceptionhandler if it
    # results in Http404 or PermissionDenied exception
    url(r'^$', forum_index, name='index'),
]


# Register API
apipatterns = [
    url(r'^', include('misago.categories.urls.api')),
    url(r'^', include('misago.markup.urls')),
    url(r'^', include('misago.threads.urls.api')),
    url(r'^', include('misago.users.urls.api')),
    url(r'^', include('misago.search.urls.api')),
]

urlpatterns += [
    url(r'^api/', include((apipatterns, 'api'), namespace='api')),
]


# Register Misago ACP
if settings.MISAGO_ADMIN_PATH:
    # Admin patterns recognised by Misago
    adminpatterns = [
        url(r'^', include('misago.admin.urls')),
    ]

    admin_prefix = r'^%s/' % settings.MISAGO_ADMIN_PATH
    urlpatterns += [
        url(admin_prefix, include((adminpatterns, 'admin'), namespace='admin')),
    ]

nuspyp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^tesseracttest/', include('tesseracttest.urls')),
    url(r'^admin/', admin.site.urls),
]

misago/acl/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _

from . import version as acl_version


def permissions_default():
    return {}


@python_2_unicode_compatible
class BaseRole(models.Model):
    name = models.CharField(max_length=255)
    special_role = models.CharField(max_length=255, null=True, blank=True)
    permissions = JSONField(default=permissions_default)

    class Meta:
        abstract = True

    def __str__(self):
        return _(self.name)

    def save(self, *args, **kwargs):
        if self.pk:
            acl_version.invalidate()
        return super(BaseRole, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        acl_version.invalidate()
        return super(BaseRole, self).delete(*args, **kwargs)


class Role(BaseRole):
    pass

misago/categories/models.py
from mptt.managers import TreeManager
from mptt.models import MPTTModel, TreeForeignKey

from django.db import models
from django.utils import six
from django.utils.encoding import python_2_unicode_compatible

from misago.acl import version as acl_version
from misago.acl.models import BaseRole
from misago.conf import settings
from misago.core.cache import cache
from misago.core.utils import slugify
from misago.threads.threadtypes import trees_map

from . import PRIVATE_THREADS_ROOT_NAME, THREADS_ROOT_NAME


CACHE_NAME = 'misago_categories_tree'


class CategoryManager(TreeManager):
    def private_threads(self):
        return self.get_special(PRIVATE_THREADS_ROOT_NAME)

    def root_category(self):
        return self.get_special(THREADS_ROOT_NAME)

    def get_special(self, special_role):
        cache_name = '%s_%s' % (CACHE_NAME, special_role)

        special_category = cache.get(cache_name, 'nada')
        if special_category == 'nada':
            special_category = self.get(special_role=special_role)
            cache.set(cache_name, special_category)
        return special_category

    def all_categories(self, include_root=False):
        tree_id = trees_map.get_tree_id_for_root(THREADS_ROOT_NAME)
        queryset = self.filter(tree_id=tree_id)
        if not include_root:
            queryset = queryset.filter(level__gt=0)
        return queryset.order_by('lft')

    def get_cached_categories_dict(self):
        categories_dict = cache.get(CACHE_NAME, 'nada')
        if categories_dict == 'nada':
            categories_dict = self.get_categories_dict_from_db()
            cache.set(CACHE_NAME, categories_dict)
        return categories_dict

    def get_categories_dict_from_db(self):
        categories_dict = {}
        for category in self.all_categories(include_root=True):
            categories_dict[category.pk] = category
        return categories_dict

    def clear_cache(self):
        cache.delete(CACHE_NAME)


@python_2_unicode_compatible
class Category(MPTTModel):
    parent = TreeForeignKey(
        'self',
        null=True,
        blank=True,
        related_name='children',
        on_delete=models.CASCADE,
    )
    special_role = models.CharField(max_length=255, null=True, blank=True)
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    is_closed = models.BooleanField(default=False)
    threads = models.PositiveIntegerField(default=0)
    posts = models.PositiveIntegerField(default=0)
    last_post_on = models.DateTimeField(null=True, blank=True)
    last_thread = models.ForeignKey(
        'misago_threads.Thread',
        related_name='+',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    last_thread_title = models.CharField(max_length=255, null=True, blank=True)
    last_thread_slug = models.CharField(max_length=255, null=True, blank=True)
    last_poster = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='+',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    last_poster_name = models.CharField(max_length=255, null=True, blank=True)
    last_poster_slug = models.CharField(max_length=255, null=True, blank=True)
    require_threads_approval = models.BooleanField(default=False)
    require_replies_approval = models.BooleanField(default=False)
    require_edits_approval = models.BooleanField(default=False)
    prune_started_after = models.PositiveIntegerField(default=0)
    prune_replied_after = models.PositiveIntegerField(default=0)
    archive_pruned_in = models.ForeignKey(
        'self',
        related_name='pruned_archive',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    css_class = models.CharField(max_length=255, null=True, blank=True)

    objects = CategoryManager()

    def __str__(self):
        return six.text_type(self.thread_type.get_category_name(self))

    @property
    def thread_type(self):
        return trees_map.get_type_for_tree_id(self.tree_id)

    def delete(self, *args, **kwargs):
        Category.objects.clear_cache()
        acl_version.invalidate()
        return super(Category, self).delete(*args, **kwargs)

    def synchronize(self):
        threads_queryset = self.thread_set.filter(is_hidden=False, is_unapproved=False)
        self.threads = threads_queryset.count()

        if self.threads:
            replies_sum = threads_queryset.aggregate(models.Sum('replies'))
            self.posts = self.threads + replies_sum['replies__sum']
        else:
            self.posts = 0

        if self.threads:
            last_thread_qs = threads_queryset.filter(is_hidden=False, is_unapproved=False)
            last_thread = last_thread_qs.order_by('-last_post_on')[:1][0]
            self.set_last_thread(last_thread)
        else:
            self.empty_last_thread()

    def delete_content(self):
        from .signals import delete_category_content
        delete_category_content.send(sender=self)

    def move_content(self, new_category):
        from .signals import move_category_content
        move_category_content.send(sender=self, new_category=new_category)

    def get_absolute_url(self):
        return self.thread_type.get_category_absolute_url(self)

    def get_last_thread_url(self):
        return self.thread_type.get_category_last_thread_url(self)

    def get_last_thread_new_url(self):
        return self.thread_type.get_category_last_thread_new_url(self)

    def get_last_post_url(self):
        return self.thread_type.get_category_last_post_url(self)

    def get_read_api_url(self):
        return self.thread_type.get_category_read_api_url(self)

    def set_name(self, name):
        self.name = name
        self.slug = slugify(name)

    def set_last_thread(self, thread):
        self.last_post_on = thread.last_post_on
        self.last_thread = thread
        self.last_thread_title = thread.title
        self.last_thread_slug = thread.slug
        self.last_poster = thread.last_poster
        self.last_poster_name = thread.last_poster_name
        self.last_poster_slug = thread.last_poster_slug

    def empty_last_thread(self):
        self.last_post_on = None
        self.last_thread = None
        self.last_thread_title = None
        self.last_thread_slug = None
        self.last_poster = None
        self.last_poster_name = None
        self.last_poster_slug = None

    def has_child(self, child):
        return child.lft > self.lft and child.rght < self.rght


class CategoryRole(BaseRole):
    pass


class RoleCategoryACL(models.Model):
    role = models.ForeignKey(
        'misago_acl.Role',
        related_name='categories_acls',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        'Category',
        related_name='category_role_set',
        on_delete=models.CASCADE,
    )
    category_role = models.ForeignKey(CategoryRole, on_delete=models.CASCADE)

misago/conf/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models

from . import utils


class SettingsGroupsManager(models.Manager):
    def ordered_alphabetically(self):
        from django.utils.translation import ugettext as _

        groups_dict = {}

        for group in self.all():
            groups_dict[_(group.name)] = group

        ordered_groups = []
        for key in groups_dict.keys():
            ordered_groups.append(groups_dict[key])
        return ordered_groups


class SettingsGroup(models.Model):
    key = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    objects = SettingsGroupsManager()


class SettingsManager(models.Manager):
    def change_setting(self, setting, dry_value=None, wet_value=None):
        if dry_value:
            return self.filter(setting=setting).update(dry_value=dry_value)
        elif wet_value:
            try:
                setting = self.get(setting=setting)
                setting.value = wet_value
                setting.save(update_fields=['dry_value'])
            except Setting.DoesNotExist:
                return 0


class Setting(models.Model):
    group = models.ForeignKey(SettingsGroup, on_delete=models.CASCADE)
    setting = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    legend = models.CharField(max_length=255, null=True, blank=True)
    order = models.IntegerField(default=0, db_index=True)
    dry_value = models.TextField(null=True, blank=True)
    default_value = models.TextField(null=True, blank=True)
    python_type = models.CharField(max_length=255, default='string')
    is_public = models.BooleanField(default=False)
    is_lazy = models.BooleanField(default=False)
    form_field = models.CharField(max_length=255, default='text')
    field_extra = JSONField()

    objects = SettingsManager()

    @property
    def value(self):
        return utils.get_setting_value(self)

    @value.setter
    def value(self, new_value):
        return utils.set_setting_value(self, new_value)

    @property
    def has_custom_value(self):
        return utils.has_custom_value(self)

misago/core/models.py
from django.db import models


class CacheVersion(models.Model):
    cache = models.CharField(max_length=128)
    version = models.PositiveIntegerField(default=0)

misago/core/testproject/models.py
class Model(object):
    def __init__(self, pk, slug):
        self.id, self.pk = pk, pk
        self.slug = slug

misago/legal/models.py
# Empty models file that triggers migrations for this app

misago/readtracker/models.py
from django.conf import settings
from django.db import models


class CategoryRead(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        'misago_categories.Category',
        on_delete=models.CASCADE,
    )
    last_read_on = models.DateTimeField()


class ThreadRead(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        'misago_categories.Category',
        on_delete=models.CASCADE,
    )
    thread = models.ForeignKey(
        'misago_threads.Thread',
        on_delete=models.CASCADE,
    )
    last_read_on = models.DateTimeField()

misago/threads/models/attachmenttype.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class AttachmentType(models.Model):
    ENABLED = 0
    LOCKED = 1
    DISABLED = 2

    name = models.CharField(max_length=255)
    extensions = models.CharField(max_length=255)
    mimetypes = models.CharField(null=True, blank=True, max_length=255)
    size_limit = models.PositiveIntegerField(default=1024)
    status = models.PositiveIntegerField(
        default=ENABLED,
        choices=[
            (ENABLED, _("Allow uploads and downloads")),
            (LOCKED, _("Allow downloads only")),
            (DISABLED, _("Disallow both uploading and downloading")),
        ],
    )

    limit_uploads_to = models.ManyToManyField('misago_acl.Role', related_name='+', blank=True)
    limit_downloads_to = models.ManyToManyField('misago_acl.Role', related_name='+', blank=True)

    def __str__(self):
        return self.name

    @property
    def is_enabled(self):
        return self.status == AttachmentType.ENABLED

    @property
    def extensions_list(self):
        if self.extensions:
            return self.extensions.split(',')
        return []

    @property
    def mimetypes_list(self):
        if self.mimetypes:
            return self.mimetypes.split(',')
        return []

misago/threads/models/pollvote.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class PollVote(models.Model):
    category = models.ForeignKey(
        'misago_categories.Category',
        on_delete=models.CASCADE,
    )
    thread = models.ForeignKey(
        'misago_threads.Thread',
        on_delete=models.CASCADE,
    )
    poll = models.ForeignKey(
        'misago_threads.Poll',
        on_delete=models.CASCADE,
    )
    voter = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    voter_name = models.CharField(max_length=255)
    voter_slug = models.CharField(max_length=255)
    voter_ip = models.GenericIPAddressField()
    voted_on = models.DateTimeField(default=timezone.now)
    choice_hash = models.CharField(max_length=12, db_index=True)

    class Meta:
        index_together = [
            ['poll', 'voter_name'],
        ]

misago/threads/models/postedit.py
import difflib

from django.conf import settings
from django.db import models
from django.utils import timezone


class PostEdit(models.Model):
    category = models.ForeignKey('misago_categories.Category', on_delete=models.CASCADE)
    thread = models.ForeignKey('misago_threads.Thread', on_delete=models.CASCADE)
    post = models.ForeignKey(
        'misago_threads.Post',
        related_name='edits_record',
        on_delete=models.CASCADE,
    )

    edited_on = models.DateTimeField(default=timezone.now)

    editor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    editor_name = models.CharField(max_length=255)
    editor_slug = models.CharField(max_length=255)
    editor_ip = models.GenericIPAddressField()

    edited_from = models.TextField()
    edited_to = models.TextField()

    class Meta:
        ordering = ['-id']

    def get_diff(self):
        return difflib.ndiff(self.edited_from.splitlines(), self.edited_to.splitlines())

misago/templates/misago/admin/base.html
{% extends "misago/admin/base_thin.html" %}
{% load static %}


{% block body %}
{% include "misago/admin/navbar.html" %}
{% include "misago/admin/messages.html" %}

{% block content %}{% endblock %}

<footer class="admin-footer">
  <div class="misago-branding text-center">
    <a href="http://misago-project.org">
      <span class="subscript">powered by</span>
      <img src="{% static 'misago/admin/img/misago.png' %}" height="22px" alt="Misago">
    </a>
  </div>
</footer>

{% include "misago/admin/logout.html" %}

{# We include JavaScript at the end of page body so it renders faster #}
<script type="text/javascript" src="{% static 'misago/admin/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-datetimepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-timestamps.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-tooltips.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-tables.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-yesnoswitch.js' %}"></script>
{% block javascripts %}{% endblock javascripts %}
{% endblock body %}

misago/templates/misago/admin/base_thin.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% trans "Misago Administration" %}{% endblock %}</title>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'misago/admin/css/style.css' %}" rel="stylesheet">
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'apple-touch-icon-57.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'apple-touch-icon-72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'apple-touch-icon-76.png' %}">
    <link rel="apple-touch-icon" sizes="80x80" href="{% static 'apple-touch-icon-80.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'apple-touch-icon-114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'apple-touch-icon-120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'apple-touch-icon-144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'apple-touch-icon-152.png' %}">
    <link rel="apple-touch-icon" sizes="167x167" href="{% static 'apple-touch-icon-167.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon-180.png' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="icon" sizes="16x16 32x32" href="{% static 'favicon.ico' %}">
  </head>
  <body>

    {% block body %}{% endblock %}

  </body>
</html>

misago/templates/misago/admin/index.html
{% extends "misago/admin/base.html" %}
{% load i18n %}


{% block title %}{% trans "Home" %} | {{ block.super }}{% endblock %}


{% block content %}
<div class="page-header">
  <div class="container">
    <h1>
      <span class="fa fa-home"></span>
      {% trans "Administration Home" %}
    </h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8">



    </div>
    <div class="col-md-4">

      <table class="table version-check">
        <thead>
          <tr>
            <th colspan="2">
              <h4>
                <span class="fa fa-github"></span>
                {% trans "Misago version" %}
              </h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="text-center">
              {% if allow_version_check %}
                {% if version_check %}
                <p class="lead text-{% if version_check.is_error %}danger{% else %}success{% endif %}">
                  {% if version_check.is_error %}
                  <span class="fa fa-times fa-lg fa-fw"></span>
                  {% else %}
                  <span class="fa fa-check fa-lg fa-fw"></span>
                  {% endif %}
                  {{ version_check.message }}
                </p>
                {% else %}
                <form method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-default">
                    <span class="fa fa-question-circle fa-fw"></span>
                    <span class="name">{% trans "Check version" %}</span>
                  </button>
                </form>
                {% endif %}
              {% else %}
                <p class="lead">
                  {% trans 'This feature requires "packaging" python module.' %}
                </p>
              {% endif %}
            </td>
          </tr>
        </tbody>
      </table>

      <table class="table">
        <thead>
          <tr>
            <th colspan="2">
              <h4>
                <span class="fa fa-database"></span>
                {% trans "DB Contents" %}
              </h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{% trans "Threads" %}</td>
            <td>{{ db_stats.threads }}</td>
          </tr>
          <tr>
            <td>{% trans "Posts" %}</td>
            <td>{{ db_stats.posts }}</td>
          </tr>
          <tr>
            <td>{% trans "Users" %}</td>
            <td>{{ db_stats.users }}</td>
          </tr>
          {% if db_stats.inactive_users %}
          <tr>
            <td>{% trans "Inactive users" %}</td>
            <td>
              <a href="{% url "misago:admin:users:accounts:index" %}?inactive=1">{{ db_stats.inactive_users }}</a>
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>

    </div>
  </div>
</div>
{% endblock content %}


{% block javascripts %}
<script type="text/javascript">
  $(function () {
    var $version_check = $('.version-check');
    var $outcome = $version_check.find('td');

    $version_check.find('form').submit(function() {
      var $form = $(this);
      var $button = $(this).find("button");
      $button.attr("disabled", "disabled");
      $button.find('.fa').attr("class", "fa fa-refresh fa-fw fa-spin");
      $button.find('.name').text("{% trans "Checking..." %}");

      $.post("{% url 'misago:admin:check-version' %}", $form.serialize(), function(data) {
        if (data.is_error) {
          var $message = $('<p class="lead text-danger"><span class="fa fa-times fa-lg fa-fw"></span></p>');
        } else {
          var $message = $('<p class="lead text-success"><span class="fa fa-check fa-lg fa-fw"></span></p>');
        }
        $message.append(" " + data.message);
        $form.fadeOut();
        $outcome.html($message);
      });

      return false;
    });
  });
</script>
{% endblock javascripts %}

misago/templates/misago/admin/login.html
{% extends "misago/admin/base_thin.html" %}
{% load i18n static %}


{% block title %}{% trans "Log in" %} | {% if target == "django" %}{% trans "Django Admin" %}{% else %}{% trans "Misago Admin" %}{% endif %}{% endblock %}


{% block body %}
<div class="login-form">

  {% if target == "misago" %}
  <div class="form-admin-logo">
    <img src="{% static 'misago/admin/img/misago.png' %}" alt="Misago">
  </div>
  {% elif target == "django" %}
  <div class="form-admin-logo">
    <img src="{% static 'misago/admin/img/django.png' %}" alt="Django">
  </div>
  {% endif  %}

  <div class="form-panel">
    <form method="POST" role="form">
      {% csrf_token %}

      <div class="form-header">
        <h1>{% trans "Administration" %}</h1>
      </div>

      <div class="form-body no-fieldsets">

        {% for error in form.non_field_errors %}
        <div class="misago-alerts">
          <p class="alert alert-danger lead">
            {{ error }}
            <br>{% trans "Please try again." %}
          </p>
        </div>
        {% endfor %}
        {% for message in messages %}
        <div class="misago-alerts">
          {% if 'success' in message.tags %}
          <p class="alert alert-success lead">
          {% elif 'warning' in message.tags %}
          <p class="alert alert-warning lead">
          {% elif 'error' in message.tags %}
          <p class="alert alert-danger lead">
          {% else %}
          <p class="alert alert-info lead">
          {% endif %}
            {{ message }}
          </p>
        </div>
        {% endfor %}

        <div class="form-group">
          <div class="control-input">
            <input type="text" name="username" class="form-control input-lg" placeholder="{% trans "Username or e-mail" %}" {% if form.username.value %}value="{{ form.username.value }}"{% endif %}>
          </div>
        </div>
        <div class="form-group">
          <div class="control-input">
            <input type="password" name="password" class="form-control input-lg" placeholder="{% trans "Password" %}">
          </div>
        </div>
        <div class="form-group">
          <div class="control-input">
            <button class="btn btn-primary btn-block btn-lg">{% trans "Sign in" %}</button>
          </div>
        </div>

      </div>


    </form>
  </div>

</div>
{% endblock body %}

misago/templates/misago/admin/logout.html
{% load i18n %}
<!-- Log out modal -->
<div class="modal fade" id="logout-modal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="logoutModalLabel">{% trans "Log out?" %}</h4>
      </div>
      <div class="modal-body">

        <div class="row">
          <div class="col-md-6">

            <form action="{% url 'misago:admin:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-block">
                <span class="fa fa-lock"></span>
                {% trans "Log out from admin" %}
              </button>
            </form>

          </div>
          <div class="col-md-6">

            <form action="{% url 'misago:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-block">
                <span class="fa fa-power-off"></span>
                {% trans "Log out completely" %}
              </button>
            </form>

          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-lg btn-block" data-dismiss="modal">{% trans "Cancel" %}</button>
      </div>
    </div>
  </div>
</div>